import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ['300', '400', '500', '700'],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Сайт животных",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${roboto.className} w-full bg-white text-zinc-700`}>
        <div className="__next">
          <Header />
          <main className="w-full" id="main">
            <div className="w-full" id="content-page">
              {children}
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
